version: "3"

services:
  db:
    image: mariadb:10.1
    container_name: "${PROJECT_NAME}_db"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_db.loadbalancer.server.port=3306"
      - "traefik.http.routers.${PROJECT_NAME}_db.rule=Host(`db.${PROJECT_BASE_URL}`)"

  php:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: ./docker/php
    volumes:
      - "./html:/var/www/html"

  web:
    container_name: "${PROJECT_NAME}_web"
    build:
      context: ./docker/web
    depends_on:
      - db
      - php
    volumes:
      - "./html:/var/www/html:ro"
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.2
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data: