<?php

/**
 * Implements hook_menu().
 */
function pwp_daily_menu() {
  return [
    'pwp_daily/data/fetch' => [
      'title' => 'PWP Daily Data Fetch',
      'page callback' => 'pwp_daily_data_fetch',
      'access callback' => TRUE,
      'file' => 'includes/data-fetch.menu.inc',
      'type' => MENU_CALLBACK,
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function pwp_daily_theme($existing, $type, $theme, $path) {
  return [
    'pwp_daily_game' => [
      'render element' => 'content',
      'template' => 'pwp_daily_game',
      'path' => pwp_daily_helpers::getPath('templates'),
    ],
  ];
}

/**
 * Implements hook_block_info().
 */
function pwp_daily_block_info() {
  return [
    'daily_game' => [
      'info' => t('Daily Game'),
      'cache' => DRUPAL_NO_CACHE,
    ],
  ];
}

/**
 * Implements hook_block_view().
 */
function pwp_daily_block_view($delta = '') {
  switch ($delta) {
    case 'daily_game':
      $block['content'] = [
        '#theme' => 'pwp_daily_game',
        '#attached' => [
          'js' => array_merge(
            pwp_daily_helpers::getSharedJSLibraries(),
            [
              [
                'type' => 'file',
                'data' => pwp_daily_helpers::getPath('js/pwp_daily_game/main.js'),
                'scope' => 'footer',
              ],
            ]
          ),
        ],
      ];

      return $block;
  }
}

/**
 * Implements hook_form_alter().
 */
function pwp_daily_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'eck__entity__form_add_daily_match_daily_match') {
    $fieldDailyTeams = $form['field_daily_teams']['und'];
    $dailyTeamsFormState = pwp_daily_helpers::getInlineEntityFormState($fieldDailyTeams, $form_state);

    if ($dailyTeamsFormState['form'] === 'add') {
      $title = 'Team ' . strtoupper(pwp_daily_constants::TEAM_KEYS[count($dailyTeamsFormState['entities'])]);
      $form['field_daily_teams']['und']['form']['title']['#default_value'] = $title;
    }

    foreach ($dailyTeamsFormState['entities'] as $key => $dailyTeam) {
      $form['field_winner']['und']['#options'][$key] = $dailyTeam['entity']->wrapper()->get('title')->value();
    }
  }
}
